**Problem 1**

Import Numpy as np

In [2]:
import numpy as np

**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [3]:
arr1D = np.array(np.random.randint(0,10,10))
print(arr1D)

[5 8 9 1 7 3 2 0 7 3]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [4]:
arr2D = np.array([[True]*3]*3)
print(arr2D)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_arr = arr[arr%2 == 1]
print(odd_arr)

[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
neg_arr = np.where(arr%2==0,arr,-1)

arr[arr%2==1]=-1 
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [7]:
np.arange(10).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

**Problem 7** 

Stack arrays a and b vertically.

In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print('*'*20)
print(b)
print('*'*20)

np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
********************
[[1 1 1 1 1]
 [1 1 1 1 1]]
********************


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Problem 8**

Stack the arrays a and b horizontally.

In [9]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**Problem 9**

Get the common items between a and b.

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# np.intersect1d(a,b)
a[[i in b for i in a]]

array([2, 2, 4, 4])

**Problem 10**

From array a remove all items present in array b

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

a[[aa not in b for aa in a]]

array([1, 2, 3, 4])

**Problem 11**

Get the positions where elements of a and b match

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.arange(a.size)[a == b]

array([1, 3, 5, 7])

**Problem 12** 

Get all items between 5 and 10 from a.

In [13]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

**Problem 13**

Swap columns 1 and 2 in the array arr.

In [14]:
arr = np.arange(9).reshape(3,3)

print(arr)
print('*'*20)

arr_t = arr.transpose()

print(arr_t)
print('*'*20)

arr_t[1],arr_t[2] = arr_t[2] ,arr_t[1][:]

print(arr_t.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
********************
[[0 3 6]
 [1 4 7]
 [2 5 8]]
********************
[[0 2 2]
 [3 5 5]
 [6 8 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [15]:
arr = np.arange(9).reshape(3,3)

print(arr)
print('*'*20)

np.

SyntaxError: invalid syntax (1490029674.py, line 6)

**Problem 15**

Reverse the rows of a 2D array arr.

In [16]:
arr = np.arange(9).reshape(3,3)

print(arr)
print('*'*20)

print(np.flipud(arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
********************
[[6 7 8]
 [3 4 5]
 [0 1 2]]


**Problem 16**

Reverse the columns of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)

print(arr)
print('+'*20)

print(np.fliplr(arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
++++++++++++++++++++
[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [17]:
arr = np.random.rand(5,3)*5+5

print(arr)

[[8.37014698 6.1858691  5.58328841]
 [9.28904206 8.14342986 7.71968188]
 [7.83658672 8.41900296 6.27031091]
 [9.80270292 8.217068   8.73321915]
 [7.81999895 7.8414567  6.16619136]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [18]:
print(arr.round(3))

[[8.37  6.186 5.583]
 [9.289 8.143 7.72 ]
 [7.837 8.419 6.27 ]
 [9.803 8.217 8.733]
 [7.82  7.841 6.166]]
